[build]
  command = "npm install && npm run build"
  publish = "public" 
  functions = "functions"

[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "16"
